import type { AchSecCode, ApplePayPaymentToken, GooglePayToken } from './transactions.js';
import type { DateRangeSearch, DateTimeString, Pagination, StringSearch } from './common.js';

/** Address stored on a customer vault record (note `line_1` / `line_2` instead of `address_line_*`). */
export interface VaultAddress {
  first_name?: string;
  last_name?: string;
  company?: string;
  line_1?: string;
  line_2?: string;
  city?: string;
  /** State code, for example `"CA"`. */
  state?: string;
  postal_code?: string;
  /** Country code, for example `"US"`. */
  country?: string;
  email?: string;
  phone?: string;
  fax?: string;
}

/** Customer flags. */
export type CustomerFlag = 'surcharge_exempt' | (string & {});

/** Flags that can be set on a stored card. */
export type StoredCardFlag =
  | 'surcharge_exempt'
  | 'applepay'
  | 'closed_contact'
  | 'contact'
  | 'locked_security'
  | 'locked_stop_recurring'
  | (string & {});

/** Query parameters accepted when storing a card / token payment method. */
export type VaultVerificationParams = {
  /** Run a $0.00 verification when storing a card. */
  validate?: boolean;
  /** Run a $1.00 authorization (never captured) when storing a card. */
  authorize?: boolean;
  /** Bypass rule engine checks for card and token verification. */
  bypass_rule_engine?: boolean;
};

/** Card payment method stored in the vault. */
export interface VaultCardInput {
  /** Custom id, 2–40 characters (`a-z`, `A-Z`, `0-9`, `.`, `-`, `_`, `^`). */
  id?: string;
  number: string;
  /** `"MMYY"` or `"MM/YY"`. */
  expiration_date: string;
}

/** ACH payment method stored in the vault. */
export interface VaultAchInput {
  /** Custom id, 2–40 characters. */
  id?: string;
  account_number: string;
  routing_number: string;
  account_type: 'checking' | 'savings';
  sec_code: Exclude<AchSecCode, 'tel'>;
}

/** Apple Pay payment method stored in the vault (always triggers a $1.00 authorization). */
export interface VaultApplePayInput {
  /** Registered Apple Pay credential id. */
  key_id: string;
  processor_id?: string;
  /** Token from Wallet.js. */
  temporary_token?: string;
  /** PKPaymentToken from Apple Pay JS. */
  pkpaymenttoken?: ApplePayPaymentToken;
}

/** Default payment method supplied when creating a customer. Set exactly one property. */
export interface VaultDefaultPayment {
  card?: VaultCardInput;
  ach?: VaultAchInput;
  /** Token generated by the Tokenizer. */
  token?: string;
  apple_pay?: VaultApplePayInput;
  google_pay_token?: GooglePayToken;
}

/** Request body for `POST /api/vault/customer`. */
export interface CreateCustomerRequest {
  /** Custom customer id, 2–40 characters. */
  id?: string;
  /** Id format for auto-generated ids. Cannot be combined with `id`. */
  id_format?: 'xid_type_last4';
  /** Max 255 characters. */
  description?: string;
  flags?: CustomerFlag[];
  default_payment?: VaultDefaultPayment;
  default_billing_address?: VaultAddress;
  default_shipping_address?: VaultAddress;
}

/** Request body for `POST /api/vault/customer/{id}`. */
export interface UpdateCustomerRequest {
  description?: string;
  notes?: string;
  flags?: CustomerFlag[];
  defaults?: {
    billing_address_id?: string;
    shipping_address_id?: string;
    /** Required if `payment_method_type` is present. */
    payment_method_id?: string;
    /** Required if `payment_method_id` is present. */
    payment_method_type?: 'card' | 'ach';
  };
}

/** Request body for `POST /api/vault/customer/search`. */
export interface CustomerSearchRequest extends Pagination {
  id?: StringSearch;
  address_id?: StringSearch;
  first_name?: StringSearch;
  last_name?: StringSearch;
  company?: StringSearch;
  address_line_1?: StringSearch;
  address_line_2?: StringSearch;
  city?: StringSearch;
  state?: StringSearch;
  postal_code?: StringSearch;
  country?: StringSearch;
  email?: StringSearch;
  phone?: StringSearch;
  fax?: StringSearch;
  payment_method_type?: StringSearch;
  billing_address_id?: StringSearch;
  shipping_address_id?: StringSearch;
  created_at?: DateRangeSearch;
  updated_at?: DateRangeSearch;
}

/** Stored address on a customer record. */
export interface StoredAddress {
  id: string;
  hash?: string;
  first_name: string;
  last_name: string;
  company: string;
  line_1: string;
  line_2: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  email: string;
  phone: string;
  fax: string;
}

/** Stored card on a customer record. */
export interface StoredCard {
  id: string;
  card_type: string;
  expiration_date: string;
  masked_number: string;
  flags?: StoredCardFlag[];
  processor_id?: string;
}

/** Stored ACH account on a customer record. */
export interface StoredAch {
  id: string;
  account_type?: string;
  sec_code?: string;
  masked_account_number?: string;
  routing_number?: string;
  flags?: string[];
  processor_id?: string;
}

/** Customer defaults. */
export interface CustomerDefaults {
  billing_address_id: string;
  shipping_address_id: string;
  payment_method_id: string;
  payment_method_type: string;
}

/** Customer details nested under `data.customer`. */
export interface CustomerDetails {
  addresses: StoredAddress[];
  defaults: CustomerDefaults;
  description: string;
  notes?: string;
  flags?: CustomerFlag[];
  payments: {
    cards: StoredCard[];
    ach: StoredAch[];
  };
  custom_fields?: unknown;
  processor_id?: string;
  shared?: boolean;
  do_not_share?: boolean;
}

/** Customer vault record. */
export interface Customer {
  id: string;
  owner_id: string;
  partner_id?: string;
  data: { customer: CustomerDetails };
  /** Populated on the create address response. */
  created_address_id?: string;
  /** Populated on the create payment method response. */
  created_payment_method_id?: string;
  created_at: DateTimeString;
  updated_at: DateTimeString;
}

/** Request body for updating a stored card. */
export interface UpdateVaultCardRequest {
  number?: string;
  /** `"MMYY"` or `"MM/YY"`. */
  expiration_date: string;
  flags?: StoredCardFlag[];
}

/** Request body for updating a stored ACH account. */
export type UpdateVaultAchRequest = Omit<VaultAchInput, 'id'>;

/** Request body for creating / updating a payment method from a Tokenizer token. */
export interface VaultTokenRequest {
  token: string;
}

/** Request body for storing a Google Pay token on a customer. */
export interface VaultGooglePayRequest {
  signature: string;
  intermediateSigningKey: Record<string, unknown>;
  protocolVersion: string;
  signedMessage: Record<string, unknown> | string;
}
